// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://czmowcarxzpgjiywzpec.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImN6bW93Y2FyeHpwZ2ppeXd6cGVjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA4NTU0MjYsImV4cCI6MjA2NjQzMTQyNn0.ohro_DO35VSLdefhw_gudnbSLGPu5VAFlHN4DvkZG2A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);